# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Node.js image
FROM node:18-alpine AS builder

# Create and set working directory
WORKDIR /app

# Copy project files to the container
COPY package.json package-lock.json ./
COPY tsconfig.json ./
COPY src ./src

# Install dependencies
RUN npm install --ignore-scripts

# Build the project
RUN npm run build

# Final image
FROM node:18-alpine

# Create and set working directory
WORKDIR /app

# Copy built files and package.json to the final image
COPY --from=builder /app/build ./build
COPY --from=builder /app/package.json ./

# Install only production dependencies
RUN npm ci --omit=dev

# Expose the port the app runs on
EXPOSE 8181

# Command to run the application
ENTRYPOINT ["node", "build/index.js"]
